# Generated by Django 4.2.4 on 2023-08-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='image',
            field=models.ManyToManyField(related_name='veiculos', to='uploader.image'),
        ),
    ]
